### ISSUE TITLE
[scrnaseq] Evaluate output options for single cell expression data

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-apps#22]
~~## Tasks related to python tests~~

- [ ] ~~Fix any easy to fix issues on the server e.g. first test failure: GET /project errors out because server returns `project_name`, but tests expect `projectid`. Fix this in the server, and file pull-requests on this repo so that @mmccorry and @ksens can review.~~
- [ ] ~~Any failure that cannot be fixed easily on the REST API server -- file a issue on this repo~~

### Background

- [`revealgenomics` R package](https://github.com/Paradigm4/revealgenomics) has `search_expression` function that returns data as a [BioConductor ExpressionSet](https://bioconductor.org/packages/release/bioc/vignettes/Biobase/inst/doc/ExpressionSetIntroduction.pdf), and that is the preferred format for handling gene-expression data at customer A.
- [`revealsc` R package](https://github.com/Paradigm4/revealgenomics-apps/tree/master/revealsc) has `revealsc_search_expression` function that currently returns data.frame output (see `_n3_` tutorial shared privately) . To satisfy the needs of customer B, we should probably attempt to return data as a decorated matrix suitable for single cell gene expression (scrnaseq) data. [`scater`](https://bioconductor.org/packages/release/bioc/html/scater.html) is one package in BioConductor community that deals with scrnaseq data. 

### Tasks

- [ ] Read / execute `scater` tutorial to see if there is any specific annotated matrix format that they prefer 
- [ ] Convert output of `revealsc_search_expression` into either a `scater` sparse matrix, or an R sparse matrix
     + [ ] Case 1: when only one `sample_id` is returned ==> one sparse matrix
     + [ ] Case 2: when multiple `sample_id`-s are returned ==> R list of sparse matrices

## Some suggestions related to REST API development setup

Just listing some of the useful best practises that I am currently using, background concepts for REST API etc. 

- [ ] General reading on HTTP protocols (GET, PUT, POST, DELETE), client-server architecture
- [ ] On the demo server, run plumber server as user `arko` and run notebook `_n1_` as user `arko2`. The aim is to separate client and server development into two user accounts. 
- [ ] Install Postman and use as a client to fire queries to the REST API server. The idea is to have a client on a completely different machine, and still be able to execute queries.

**Comment by ksens** [comment]
@arko-bhattacharya Just FYI - edited the original ticket significantly. Best to read on Github itself (instead of the original email notification). Thanks.

**Comment by ksens** [comment]
Added another update to the original ticket: Added a `Background` section describing the various packages and functions involved -- unfortunately there are quite a few :)

**Comment by ksens** [comment]
@arko-bhattacharya 

Have moved the python tests related work to #29. Renaming this issue to focus mainly on the expression data output related task. 

The following code shows the current implementation for `search_expression`:

```R
rm(list=ls())
creds_file = '~/.scidb_secure_user_auth'
rg_connect(username = read_json(creds_file)$`user-name`, password = read_json(creds_file)$`user-password`)
res1 = search_expression(
  measurementset = get_measurementsets(measurementset_id = 1), 
  feature = search_features(gene_symbol = 'EGFR'), 
  formExpressionSet = FALSE)
head(res1, 2)
#   dataset_version dataset_id measurementset_id biosample_id feature_id    value
# 1               1          1                 1            1       8865 1076.070
# 2               1          1                 1            2       8865  196.697

res2 = search_expression(
  measurementset = get_measurementsets(measurementset_id = 1), 
  feature = search_features(gene_symbol = c('EGFR', 'KRAS')), 
  formExpressionSet = TRUE)
res2
# ExpressionSet (storageMode: lockedEnvironment)
# assayData: 2 features, 151 samples 
# element names: exprs 
# protocolData: none
# phenoData
# sampleNames: TCGA-AB-2908-03A-01T-0740-13 TCGA-AB-2929-03A-01T-0735-13 ...
# TCGA-AB-3000-03A-01T-0736-13 (151 total)
# varLabels: biosample_id dataset_version ... years_smoked (64 total)
# varMetadata: labelDescription
# featureData
# featureNames: KRAS EGFR
# fvarLabels: feature_id gene_symbol_id ... width (15 total)
# fvarMetadata: labelDescription
# experimentData: use 'experimentData(object)'
# Annotation:  
class(res2)
# [1] "ExpressionSet"
# attr(,"package")
# [1] "Biobase"

exprs(res2)[, 1:3]
#      TCGA-AB-2908-03A-01T-0740-13 TCGA-AB-2929-03A-01T-0735-13 TCGA-AB-2937-03A-01T-0734-13
# KRAS                   201889.594                  196738.4062                  226368.2969
# EGFR                     1076.074                     196.6974                     151.2834
```

Note how the first output is a data.frame. However the preferred output for regular gene expression data is the Bioconductor ExpressionSet object. 

The goal of this ticket is to find if there is a similar preferred format for single cell gene expression data (because the matrix is much too sparse in some single cell gene expression datasets, it is unlikely that the Bioconductor ExpressionSet object will suffice for that). 

We will probably bring up this question about preferred output format for scrnaseq in our next weekly meeting with scrnaseq folks, but it would be good to do some homework before we ask them.

**Comment by ksens** [comment]
@arko-bhattacharya 
Got inputs from our scrnaeq principal. There seems to be no preferred output format or R package for returning scrnaseq data. It should be OK to return them as R sparse matrices, along with some attached annotations:

- Feature information
    + ENSEMBL gene id
    + Hugo gene symbol
    + Feature reference (which build was used etc.)
- database index `cellid` should suffice (or potentially barcodes might be required)
- `sampleid` (human readable)

Please let me know if you have any other items to add from your investigation. Otherwise it should be OK to close this issue.

Now, that we know we will have to work with generic R sparse matrices, the work shifts to integrating [PR 82 on the main `revealgenomics` API](https://github.com/Paradigm4/revealgenomics/pull/82). When we meet next, I can describe the following regarding the pending PR:
- the major work done on this PR includes the optimization described at https://github.com/Paradigm4/revealgenomics/issues/63
- why this PR could not be merged yet
- potential steps to merge PR

**Comment by ksens** [comment]
Closing the issue.
